---
kind: pipeline
type: docker
name: compliance

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - tag
    - pull_request

volumes:
  - name: deps
    temp: {}

steps:
  - name: deps-frontend
    image: node:16
    pull: always
    commands:
      - make deps-frontend

  - name: deps-backend
    image: golang:1.17
    pull: always
    commands:
      - make deps-backend
    volumes:
      - name: deps
        path: /go

  - name: lint-frontend
    image: node:16
    commands:
      - make lint-frontend
    depends_on: [deps-frontend]

  - name: lint-backend
    image: gitea/test_env:linux-amd64  # https://gitea.com/gitea/test-env
    pull: always
    commands:
      - make lint-backend
    environment:
      GOPROXY: https://goproxy.cn # proxy.golang.org is blocked in China, this proxy is not
      GOSUMDB: sum.golang.org
      TAGS: bindata sqlite sqlite_unlock_notify
    depends_on: [deps-backend]

  - name: lint-backend-windows
    image: gitea/test_env:linux-amd64  # https://gitea.com/gitea/test-env
    commands:
      - make golangci-lint vet
    environment:
      GOPROXY: https://goproxy.cn # proxy.golang.org is blocked in China, this proxy is not
      GOSUMDB: sum.golang.org
      TAGS: bindata sqlite sqlite_unlock_notify
      GOOS: windows
      GOARCH: amd64
    depends_on: [deps-backend]

  - name: lint-backend-gogit
    image: gitea/test_env:linux-amd64  # https://gitea.com/gitea/test-env
    commands:
      - make lint-backend
    environment:
      GOPROXY: https://goproxy.cn # proxy.golang.org is blocked in China, this proxy is not
      GOSUMDB: sum.golang.org
      TAGS: bindata gogit sqlite sqlite_unlock_notify
    depends_on: [deps-backend]

  - name: checks-frontend
    image: node:16
    commands:
      - make checks-frontend
    depends_on: [deps-frontend]

  - name: checks-backend
    image: golang:1.17
    commands:
      - make checks-backend
    depends_on: [deps-backend]
    volumes:
      - name: deps
        path: /go

  - name: test-frontend
    image: node:16
    commands:
      - make test-frontend
    depends_on: [lint-frontend]

  - name: build-frontend
    image: node:16
    commands:
      - make frontend
    depends_on: [test-frontend]

  - name: build-backend-no-gcc
    image: golang:1.16 # this step is kept as the lowest version of golang that we support
    pull: always
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
    commands:
      - go build -o gitea_no_gcc # test if build succeeds without the sqlite tag
    depends_on: [deps-backend, checks-backend]
    volumes:
      - name: deps
        path: /go

  - name: build-backend-arm64
    image: golang:1.17
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
      GOOS: linux
      GOARCH: arm64
      TAGS: bindata gogit
    commands:
      - make backend # test cross compile
      - rm ./gitea # clean
    depends_on: [deps-backend, checks-backend]
    volumes:
      - name: deps
        path: /go

  - name: build-backend-windows
    image: golang:1.17
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
      GOOS: windows
      GOARCH: amd64
      TAGS: bindata gogit
    commands:
      - go build -o gitea_windows
    depends_on: [deps-backend, checks-backend]
    volumes:
      - name: deps
        path: /go

  - name: build-backend-386
    image: golang:1.17
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
      GOOS: linux
      GOARCH: 386
    commands:
      - go build -o gitea_linux_386 # test if compatible with 32 bit
    depends_on: [deps-backend, checks-backend]
    volumes:
      - name: deps
        path: /go

---
kind: pipeline
type: docker
name: release-latest

platform:
  os: linux
  arch: amd64

depends_on:
  - compliance

workspace:
  base: /source
  path: /

trigger:
  branch:
    - main
    - "release/dcs/*"
  event:
    - push

volumes:
  - name: deps
    temp: {}

steps:
  - name: fetch-tags
    image: docker:git
    pull: always
    commands:
      - git fetch --tags --force

  - name: deps-frontend
    image: node:16
    pull: always
    commands:
      - make deps-frontend

  - name: deps-backend
    image: golang:1.17
    pull: always
    commands:
      - make deps-backend
    volumes:
      - name: deps
        path: /go

  - name: static
    image: techknowlogick/xgo:go-1.17.x
    pull: always
    commands:
      - curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
      - export PATH=$PATH:$GOPATH/bin
      - make release
    environment:
      GOPROXY: https://goproxy.cn # proxy.golang.org is blocked in China, this proxy is not
      TAGS: bindata sqlite sqlite_unlock_notify sqlite_json
    volumes:
      - name: deps
        path: /go

  - name: release-branch
    image: woodpeckerci/plugin-s3:latest
    pull: always
    settings:
      acl: public-read
      bucket: gitea-artifacts
      endpoint: https://ams3.digitaloceanspaces.com
      path_style: true
      source: "dist/release/*"
      strip_prefix: dist/release/
      target: "/gitea/${DRONE_BRANCH##release/dcs/v}"
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    when:
      branch:
        - "release/dcs/*"
      event:
        - push

  - name: release-main
    image: woodpeckerci/plugin-s3:latest
    settings:
      acl: public-read
      bucket: gitea-artifacts
      endpoint: https://ams3.digitaloceanspaces.com
      path_style: true
      source: "dist/release/*"
      strip_prefix: dist/release/
      target: /dcs/main
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    when:
      branch:
        - main
      event:
        - push

---
kind: pipeline
name: release-version

platform:
  os: linux
  arch: amd64

depends_on:
  - compliance

workspace:
  base: /source
  path: /

trigger:
  event:
    - tag

volumes:
  - name: deps
    temp: {}

steps:
  - name: fetch-tags
    image: docker:git
    pull: always
    commands:
      - git fetch --tags --force

  - name: deps-frontend
    image: node:16
    pull: always
    commands:
      - make deps-frontend

  - name: deps-backend
    image: golang:1.17
    pull: always
    commands:
      - make deps-backend
    volumes:
      - name: deps
        path: /go

  - name: static
    image: techknowlogick/xgo:go-1.17.x
    pull: always
    commands:
      - curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
      - export PATH=$PATH:$GOPATH/bin
      - make release
    environment:
      GOPROXY: https://goproxy.cn # proxy.golang.org is blocked in China, this proxy is not
      TAGS: bindata sqlite sqlite_unlock_notify sqlite_json
    depends_on: [fetch-tags]
    volumes:
      - name: deps
        path: /go

  - name: release-tag
    image: woodpeckerci/plugin-s3:latest
    pull: always
    settings:
      acl: public-read
      bucket: gitea-artifacts
      endpoint: https://ams3.digitaloceanspaces.com
      path_style: true
      source: "dist/release/*"
      strip_prefix: dist/release/
      target: "/gitea/${DRONE_TAG##v}"
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key

  - name: github
    image: plugins/github-release:1
    pull: always
    settings:
      files:
        - "dist/release/*"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token

---
kind: pipeline
type: docker
name: docker-linux-amd64-release-version

platform:
  os: linux
  arch: amd64

depends_on:
  - compliance

trigger:
  ref:
  - "refs/tags/**"
  event:
    exclude:
    - cron

steps:
  - name: fetch-tags
    image: docker:git
    pull: always
    commands:
      - git fetch --tags --force

  - name: publish
    image: techknowlogick/drone-docker:latest
    pull: always
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

  - name: publish-rootless
    image: techknowlogick/drone-docker:latest
    settings:
      dockerfile: Dockerfile.rootless
      auto_tag: true
      auto_tag_suffix: linux-amd64-rootless
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

---
kind: pipeline
type: docker
name: docker-linux-amd64-release

platform:
  os: linux
  arch: amd64

depends_on:
  - compliance

trigger:
  ref:
  - refs/heads/main
  event:
    exclude:
    - cron

steps:
  - name: fetch-tags
    image: docker:git
    pull: always
    commands:
      - git fetch --tags --force

  - name: publish
    image: techknowlogick/drone-docker:latest
    pull: always
    settings:
      auto_tag: false
      tags: dev-linux-amd64
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

  - name: publish-rootless
    image: techknowlogick/drone-docker:latest
    settings:
      dockerfile: Dockerfile.rootless
      auto_tag: false
      tags: dev-linux-amd64-rootless
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

---
kind: pipeline
name: docker-linux-amd64-release-branch

platform:
  os: linux
  arch: amd64

depends_on:
  - compliance

trigger:
  ref:
  - "refs/heads/release/dcs/v*"
  event:
    exclude:
    - cron

steps:
  - name: fetch-tags
    image: docker:git
    pull: always
    commands:
      - git fetch --tags --force

  - name: publish
    image: techknowlogick/drone-docker:latest
    pull: always
    settings:
      auto_tag: false
      tags: ${DRONE_BRANCH##release/dcs/v}-dev-linux-amd64
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

  - name: publish-rootless
    image: techknowlogick/drone-docker:latest
    settings:
      dockerfile: Dockerfile.rootless
      auto_tag: false
      tags: ${DRONE_BRANCH##release/dcs/v}-dev-linux-amd64-rootless
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

---
kind: pipeline
type: docker
name: docker-linux-arm64-dry-run

platform:
  os: linux
  arch: arm64

depends_on:
  - compliance

trigger:
  ref:
  - "refs/pull/**"

steps:
  - name: dryrun
    image: techknowlogick/drone-docker:latest
    pull: always
    settings:
      dry_run: true
      repo: unfoldingword/dcs
      tags: linux-arm64
      build_args:
        - GOPROXY=https://goproxy.cn
    environment:
      PLUGIN_MIRROR:
        from_secret: plugin_mirror
    when:
      event:
        - pull_request

---
kind: pipeline
type: docker
name: docker-linux-arm64-release-version

platform:
  os: linux
  arch: arm64

depends_on:
  - compliance

depends_on:
  - compliance

trigger:
  ref:
  - "refs/tags/**"
  event:
    exclude:
    - cron

steps:
  - name: fetch-tags
    image: docker:git
    pull: always
    commands:
      - git fetch --tags --force

  - name: publish
    image: techknowlogick/drone-docker:latest
    pull: always
    settings:
      auto_tag: true
      auto_tag_suffix: linux-arm64
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

  - name: publish-rootless
    image: techknowlogick/drone-docker:latest
    settings:
      dockerfile: Dockerfile.rootless
      auto_tag: true
      auto_tag_suffix: linux-arm64-rootless
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

---
kind: pipeline
type: docker
name: docker-linux-arm64-release

platform:
  os: linux
  arch: arm64

depends_on:
  - compliance

trigger:
  ref:
  - refs/heads/main
  event:
    exclude:
    - cron

steps:
  - name: fetch-tags
    image: docker:git
    pull: always
    commands:
      - git fetch --tags --force

  - name: publish
    image: techknowlogick/drone-docker:latest
    pull: always
    settings:
      auto_tag: false
      tags: dev-linux-arm64
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

  - name: publish-rootless
    image: techknowlogick/drone-docker:latest
    settings:
      dockerfile: Dockerfile.rootless
      auto_tag: false
      tags: dev-linux-arm64-rootless
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

---
kind: pipeline
name: docker-linux-arm64-release-branch

platform:
  os: linux
  arch: arm64

depends_on:
  - compliance

trigger:
  ref:
  - "refs/heads/release/dcs/v*"
  event:
    exclude:
    - cron

steps:
  - name: fetch-tags
    image: docker:git
    pull: always
    commands:
      - git fetch --tags --force

  - name: publish
    image: techknowlogick/drone-docker:latest
    pull: always
    settings:
      auto_tag: false
      tags: ${DRONE_BRANCH##release/dcs/v}-dev-linux-arm64
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request

  - name: publish-rootless
    image: techknowlogick/drone-docker:latest
    settings:
      dockerfile: Dockerfile.rootless
      auto_tag: false
      tags: ${DRONE_BRANCH##release/dcs/v}-dev-linux-arm64-rootless
      repo: unfoldingword/dcs
      build_args:
        - GOPROXY=https://goproxy.cn
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
        - pull_request
