version: "3"

services:
  dcs:
    build: .
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea-main
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea      
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data-main:/data
    ports:
      - "${DCS_PORT-3000}:3000"
      - "222:22"
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea-main
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  gitea:
    external: false
