version: "3"

services:
  dcs:
    container_name: dcs
    image: dcs-dev:latest
    build:
      context: .
      dockerfile: Dockerfile-dev
    user: "${UID}:${GID}"
    environment:
      - USER_UID="${UID}"
      - USER_GID="${GID}"
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea-release
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - TAGS=bindata sqlite sqlite_unlock_notify sqlite_json
    restart: always
    networks:
      - gitea
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data-release:/data
      - .:/go/src/code.gitea.io/gitea
    ports:
      - "${DCS_PORT-3000}:80"
      - "222:22"
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea-release
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  gitea:
    external: false
